// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using yash.Data.EF;

namespace yash.Data.Migrations
{
    [DbContext(typeof(YashDbContext))]
    [Migration("20210223104758_add_data_seeding")]
    partial class add_data_seeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("yash.Data.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<bool>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "cmt8",
                            Email = "minhl93172@gmail.com",
                            FirstName = "Minh",
                            LastName = "Le",
                            Password = "123",
                            Role = true
                        },
                        new
                        {
                            Id = 2,
                            Address = "cmt8",
                            Email = "tuan123@gmail.com",
                            FirstName = "Tuan",
                            LastName = "Bui",
                            Password = "123",
                            Role = false
                        });
                });

            modelBuilder.Entity("yash.Data.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("yash.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Anniversary"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Birthday"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Wedding"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Engagement"
                        });
                });

            modelBuilder.Entity("yash.Data.Entities.Certification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LinkUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Certifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LinkUrl = "http://www.bis.org.in/",
                            Name = "BIS Hallmark"
                        },
                        new
                        {
                            Id = 2,
                            LinkUrl = "https://sgl-labs.com/",
                            Name = "SGL"
                        },
                        new
                        {
                            Id = 3,
                            LinkUrl = "https://www.igi.org/",
                            Name = "IGI"
                        });
                });

            modelBuilder.Entity("yash.Data.Entities.Diamond", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiamondShape")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Diamonds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiamondShape = "round",
                            Price = 7291f
                        },
                        new
                        {
                            Id = 2,
                            DiamondShape = "princess",
                            Price = 4799f
                        },
                        new
                        {
                            Id = 3,
                            DiamondShape = "oval",
                            Price = 5362f
                        },
                        new
                        {
                            Id = 4,
                            DiamondShape = "cushion",
                            Price = 4229f
                        },
                        new
                        {
                            Id = 5,
                            DiamondShape = "pear",
                            Price = 5802f
                        },
                        new
                        {
                            Id = 6,
                            DiamondShape = "radiant",
                            Price = 4443f
                        },
                        new
                        {
                            Id = 7,
                            DiamondShape = "emerald",
                            Price = 4476f
                        },
                        new
                        {
                            Id = 8,
                            DiamondShape = "asscher",
                            Price = 4137f
                        },
                        new
                        {
                            Id = 9,
                            DiamondShape = "marquise",
                            Price = 5596f
                        },
                        new
                        {
                            Id = 10,
                            DiamondShape = "heart",
                            Price = 5536f
                        });
                });

            modelBuilder.Entity("yash.Data.Entities.Gold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GoldCarat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Golds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GoldCarat = "14kt",
                            Price = 1034.8f
                        },
                        new
                        {
                            Id = 2,
                            GoldCarat = "18kt",
                            Price = 1338.9f
                        });
                });

            modelBuilder.Entity("yash.Data.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CertifyId")
                        .HasColumnType("int");

                    b.Property<float>("DiamondCarat")
                        .HasColumnType("real");

                    b.Property<int>("DiamondId")
                        .HasColumnType("int");

                    b.Property<int>("GoldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<float>("GoldWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(1f);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("RingSizeId")
                        .HasColumnType("int");

                    b.Property<float>("TotalMaking")
                        .HasColumnType("real");

                    b.Property<int>("WastageInPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(20);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CertifyId");

                    b.HasIndex("DiamondId");

                    b.HasIndex("GoldId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RingSizeId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CertifyId = 1,
                            DiamondCarat = 0.1f,
                            DiamondId = 2,
                            GoldId = 2,
                            GoldWeight = 0f,
                            Name = "The Jhonita Two Finger Ring",
                            ProductId = 1,
                            Quantity = 5,
                            RingSizeId = 6,
                            TotalMaking = 26309f,
                            WastageInPercentage = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CertifyId = 2,
                            DiamondCarat = 0.12f,
                            DiamondId = 3,
                            GoldId = 2,
                            GoldWeight = 0f,
                            Name = "The Rudri Ring",
                            ProductId = 1,
                            Quantity = 4,
                            RingSizeId = 10,
                            TotalMaking = 33609f,
                            WastageInPercentage = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CertifyId = 3,
                            DiamondCarat = 0.12f,
                            DiamondId = 1,
                            GoldId = 1,
                            GoldWeight = 0f,
                            Name = "The Maruwani Ring",
                            ProductId = 1,
                            Quantity = 5,
                            RingSizeId = 20,
                            TotalMaking = 27731f,
                            WastageInPercentage = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CertifyId = 1,
                            DiamondCarat = 0.07f,
                            DiamondId = 1,
                            GoldId = 1,
                            GoldWeight = 0f,
                            Name = "The Arcane Stud Earrings",
                            ProductId = 2,
                            Quantity = 4,
                            RingSizeId = 10,
                            TotalMaking = 15000f,
                            WastageInPercentage = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CertifyId = 2,
                            DiamondCarat = 0.108f,
                            DiamondId = 1,
                            GoldId = 2,
                            GoldWeight = 0f,
                            Name = "The Purva Drop Earrings",
                            ProductId = 2,
                            Quantity = 5,
                            RingSizeId = 10,
                            TotalMaking = 21593f,
                            WastageInPercentage = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CertifyId = 3,
                            DiamondCarat = 0.04f,
                            DiamondId = 2,
                            GoldId = 1,
                            GoldWeight = 0f,
                            Name = "The Mahima Drop Earrings",
                            ProductId = 2,
                            Quantity = 4,
                            RingSizeId = 10,
                            TotalMaking = 23000f,
                            WastageInPercentage = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CertifyId = 1,
                            DiamondCarat = 0.04f,
                            DiamondId = 3,
                            GoldId = 2,
                            GoldWeight = 0f,
                            Name = "The Mulam Pendant",
                            ProductId = 3,
                            Quantity = 4,
                            RingSizeId = 10,
                            TotalMaking = 21752f,
                            WastageInPercentage = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CertifyId = 2,
                            DiamondCarat = 0.025f,
                            DiamondId = 3,
                            GoldId = 1,
                            GoldWeight = 0f,
                            Name = "The Rohal Pendant",
                            ProductId = 3,
                            Quantity = 5,
                            RingSizeId = 10,
                            TotalMaking = 11000f,
                            WastageInPercentage = 0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CertifyId = 3,
                            DiamondCarat = 0.029f,
                            DiamondId = 1,
                            GoldId = 2,
                            GoldWeight = 0f,
                            Name = "The Ambrosia Pendant",
                            ProductId = 3,
                            Quantity = 4,
                            RingSizeId = 10,
                            TotalMaking = 7962f,
                            WastageInPercentage = 0
                        });
                });

            modelBuilder.Entity("yash.Data.Entities.ItemImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("ItemImageUrl")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDefault = true,
                            ItemId = 1,
                            ItemImageUrl = "images_product/ring1.png",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            IsDefault = false,
                            ItemId = 1,
                            ItemImageUrl = "images_product/ring2.png",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            IsDefault = true,
                            ItemId = 2,
                            ItemImageUrl = "images_product/ring3.png",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 4,
                            IsDefault = false,
                            ItemId = 2,
                            ItemImageUrl = "images_product/ring4.png",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 5,
                            IsDefault = true,
                            ItemId = 3,
                            ItemImageUrl = "images_product/ring5.png",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 6,
                            IsDefault = false,
                            ItemId = 3,
                            ItemImageUrl = "images_product/ring6.png",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 7,
                            IsDefault = true,
                            ItemId = 4,
                            ItemImageUrl = "images_product/earring1.png",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 8,
                            IsDefault = false,
                            ItemId = 4,
                            ItemImageUrl = "images_product/earring2.png",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 9,
                            IsDefault = true,
                            ItemId = 5,
                            ItemImageUrl = "images_product/earring3.png",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 10,
                            IsDefault = false,
                            ItemId = 5,
                            ItemImageUrl = "images_product/earring4.png",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 11,
                            IsDefault = true,
                            ItemId = 6,
                            ItemImageUrl = "images_product/earring5.png",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 12,
                            IsDefault = false,
                            ItemId = 6,
                            ItemImageUrl = "images_product/earring6.png",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 13,
                            IsDefault = true,
                            ItemId = 7,
                            ItemImageUrl = "images_product/pendant1.png",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 14,
                            IsDefault = false,
                            ItemId = 7,
                            ItemImageUrl = "images_product/pendant2.png",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 15,
                            IsDefault = true,
                            ItemId = 8,
                            ItemImageUrl = "images_product/pendant3.png",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 16,
                            IsDefault = false,
                            ItemId = 8,
                            ItemImageUrl = "images_product/pendant4.png",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 17,
                            IsDefault = true,
                            ItemId = 9,
                            ItemImageUrl = "images_product/pendant5.png",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 18,
                            IsDefault = false,
                            ItemId = 9,
                            ItemImageUrl = "images_product/pendant6.png",
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("yash.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShipAddress")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ShipEmail")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("ShipName")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ShipPhoneNumber")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("yash.Data.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("yash.Data.Entities.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "RINGS"
                        },
                        new
                        {
                            Id = 2,
                            Name = "EARRINGS"
                        },
                        new
                        {
                            Id = 3,
                            Name = "PENDANTS"
                        });
                });

            modelBuilder.Entity("yash.Data.Entities.RingSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SizeNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RingSizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SizeNumber = 6
                        },
                        new
                        {
                            Id = 2,
                            SizeNumber = 7
                        },
                        new
                        {
                            Id = 3,
                            SizeNumber = 8
                        },
                        new
                        {
                            Id = 4,
                            SizeNumber = 9
                        },
                        new
                        {
                            Id = 5,
                            SizeNumber = 10
                        },
                        new
                        {
                            Id = 6,
                            SizeNumber = 11
                        },
                        new
                        {
                            Id = 7,
                            SizeNumber = 12
                        },
                        new
                        {
                            Id = 8,
                            SizeNumber = 13
                        },
                        new
                        {
                            Id = 9,
                            SizeNumber = 14
                        },
                        new
                        {
                            Id = 10,
                            SizeNumber = 15
                        },
                        new
                        {
                            Id = 11,
                            SizeNumber = 16
                        },
                        new
                        {
                            Id = 12,
                            SizeNumber = 17
                        },
                        new
                        {
                            Id = 13,
                            SizeNumber = 18
                        },
                        new
                        {
                            Id = 14,
                            SizeNumber = 19
                        },
                        new
                        {
                            Id = 15,
                            SizeNumber = 20
                        },
                        new
                        {
                            Id = 16,
                            SizeNumber = 21
                        },
                        new
                        {
                            Id = 17,
                            SizeNumber = 22
                        },
                        new
                        {
                            Id = 18,
                            SizeNumber = 23
                        },
                        new
                        {
                            Id = 19,
                            SizeNumber = 24
                        },
                        new
                        {
                            Id = 20,
                            SizeNumber = 25
                        },
                        new
                        {
                            Id = 21,
                            SizeNumber = 26
                        },
                        new
                        {
                            Id = 22,
                            SizeNumber = 27
                        },
                        new
                        {
                            Id = 23,
                            SizeNumber = 28
                        },
                        new
                        {
                            Id = 24,
                            SizeNumber = 29
                        },
                        new
                        {
                            Id = 25,
                            SizeNumber = 30
                        });
                });

            modelBuilder.Entity("yash.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CurrentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "CMT8",
                            City = "HCM",
                            CurrentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "minh123@gmail.com",
                            FirstName = "Minh",
                            LastName = "Le",
                            Password = "123"
                        },
                        new
                        {
                            Id = 2,
                            Address = "3 Thang 2",
                            City = "HCM",
                            CurrentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tuan123@gmail.com",
                            FirstName = "Tuan",
                            LastName = "Bui",
                            Password = "123"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Hoang Sa",
                            City = "HCM",
                            CurrentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DOB = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin123@gmail.com",
                            FirstName = "admin",
                            LastName = "admin",
                            Password = "123"
                        });
                });

            modelBuilder.Entity("yash.Data.Entities.Cart", b =>
                {
                    b.HasOne("yash.Data.Entities.Item", "Item")
                        .WithMany("Carts")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("yash.Data.Entities.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("yash.Data.Entities.Item", b =>
                {
                    b.HasOne("yash.Data.Entities.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("yash.Data.Entities.Certification", "Certification")
                        .WithMany("Items")
                        .HasForeignKey("CertifyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("yash.Data.Entities.Diamond", "Diamond")
                        .WithMany("Items")
                        .HasForeignKey("DiamondId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("yash.Data.Entities.Gold", "Gold")
                        .WithMany("Items")
                        .HasForeignKey("GoldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("yash.Data.Entities.ProductType", "ProductType")
                        .WithMany("Items")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("yash.Data.Entities.RingSize", "RingSize")
                        .WithMany("Items")
                        .HasForeignKey("RingSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("yash.Data.Entities.ItemImage", b =>
                {
                    b.HasOne("yash.Data.Entities.Item", "Item")
                        .WithMany("ItemImages")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("yash.Data.Entities.Order", b =>
                {
                    b.HasOne("yash.Data.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("yash.Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("yash.Data.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("yash.Data.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
